{% set version = "1.7.2" %}

package:
  name: geotiff
  version: {{ version }}

source:
  url: http://download.osgeo.org/geotiff/libgeotiff/libgeotiff-{{ version }}.tar.gz
  sha256: 93c51fe139661d78092b30449293d28c230041d4e33ec3cabadeb167745c1177
  patches:
    - cmake.patch

build:
  number: 0
  skip: true  # [(win and vc<14) or ppc64le]
  run_exports:
    # https://abi-laboratory.pro/?view=timeline&l=libgeotiff
    - {{ pin_subpackage('geotiff', max_pin='x.x') }}

requirements:
  build:
    # cmake 3.28 had windows build failure GH63
    - cmake <3.28  # [win]
    - cmake  # [not win]
    - make
    - gnuconfig  # [unix]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
  host:
    - proj
    - zlib
    - libjpeg-turbo
    - libtiff
  run:
    - proj
    - zlib
    - libjpeg-turbo
    - libtiff

test:
  commands:
    - test -f $PREFIX/lib/libgeotiff${SHLIB_EXT}  # [not win]
    - if not exist %LIBRARY_LIB%\\geotiff_i.lib exit 1  # [win]
    - if not exist %LIBRARY_BIN%\\geotiff.dll exit 1  # [win]

about:
  home: https://trac.osgeo.org/geotiff
  license: MIT
  license_file: LICENSE
  summary: TIFF based interchange format for georeferenced raster imagery
  description: |
    GeoTIFF represents an effort by over 160 different remote sensing,
    GIS, cartographic, and surveying related companies and organizations
    to establish a TIFF based interchange format for georeferenced raster imagery.

extra:
  recipe-maintainers:
    - akrherz
    - gillins
    - ocefpaf
    - xylar
