{% set version = "1.4.2" %}

package:
  name: geotiff
  version: {{ version }}

source:
  url: http://download.osgeo.org/geotiff/libgeotiff/libgeotiff-{{ version }}.tar.gz
  sha256: ad87048adb91167b07f34974a8e53e4ec356494c29f1748de95252e8f81a5e6e

build:
  number: 1005

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - proj4
    - zlib
    - jpeg
    - libtiff
  run:
    - proj4
    - zlib
    - jpeg
    - libtiff

test:
  commands:
    - test -f $PREFIX/lib/libgeotiff${SHLIB_EXT}  # [not win]
    - if not exist %LIBRARY_LIB%\\geotiff_i.lib exit 1  # [win]
    - if not exist %LIBRARY_BIN%\\geotiff.dll exit 1  # [win]

about:
  home: https://trac.osgeo.org/geotiff
  license: MIT
  license_file: LICENSE
  summary: 'TIFF based interchange format for georeferenced raster imagery'
  description: |
    GeoTIFF represents an effort by over 160 different remote sensing,
    GIS, cartographic, and surveying related companies and organizations
    to establish a TIFF based interchange format for georeferenced raster imagery.

extra:
  recipe-maintainers:
    - gillins
    - ocefpaf
